
mocs = ../moc_sboard.o ../moc_karate.o ../moc_football.o

all: sboard_test

sboard_test: sboard.o test.o
	$(LINK) $(LFLAGS) -o sboard_test ../sboard.o ../karate.o ../football.o $(mocs) sboard.o test.o $(LIBS)

sboard.h: ../sboard.h
	cp ../sboard.h .
	sed -i 's/private/protected/' sboard.h
	sed -i 's%ui_%../ui_%' sboard.h

test.o: test.cpp tsboard.h
	$(CXX) $(CXXFLAGS) $(INCPATH) -c test.cpp

sboard.o: sboard.cpp sboard.h tsboard.h
	$(CXX) $(CXXFLAGS) $(INCPATH) -c sboard.cpp