language: cpp

compiler:
  - gcc
  - clang

before_install: sudo apt-get update -qq && sudo apt-get install libqt4-dev;

script:
  - if [[ "$CC" == "clang" ]]; then SPEC="-spec unsupported/linux-clang" ;fi; qmake -r $SPEC
  - make

branches:
  only: master

os: linux
