language: cpp

compiler:
  - gcc
  - clang

before_install: sudo apt-get update -qq && sudo apt-get install libqt4-dev;

script:
  - if [[ "$CC" == "clang" ]]; then SPEC="-spec unsupported/linux-clang" ;fi; qmake -r $SPEC
  - make
  - echo "running Test on Score Board"
  - cd score_board; chmod +x tests/*;tests/score_board.sh; cd -
  - cat score_board/master.log

branches:
  only: master

os: linux
