language: cpp

sudo: required 

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libqt4-dev
      - libqt4-sql-sqlite

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start 
  - sudo apt-get install netcat-traditional -y 
  - sudo update-alternatives --set nc /bin/nc.traditional 

script:
  - if [[ "$CC" == "clang" ]]; then SPEC="-spec unsupported/linux-clang" ;fi; qmake -r $SPEC
  - make
  - echo "testing MasterServer Board"
  - cd master_table; ./MasterServer --test-only; cd -
  - echo "running Test on Score Board"
  - cd score_board; chmod +x tests/*;tests/score_board.sh
  - cd -; cat score_board/master.log

branches:
  only: master

os: linux
