######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 11 02:44:20 2010
######################################################################

TEMPLATE = subdirs
SUBDIRS = common_lib master_table score_board
