######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 11 02:44:28 2010
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml sql network
# Input
HEADERS += main.com.h \
    unit.h \
    board.h \
    judge.h
SOURCES += main.com.cpp \
    board.cpp \
    judge.cpp \
    unit.cpp
